import logging

logger = logging.getLogger(__name__)


def evaluate_context(llm, query, documents):
    if not documents:
        logger.warning("No documents available for context evaluation")
        return "not_relevant"

    context = "\n\n".join(document.page_content for document, _ in documents)

    prompt = f"""You are evaluating retrieved context for a RAG system.

    Question:
    {query}

    Retrieved Context:
    {context}

    Determine whether the retrieved context contains information that is relevant to answering the question.

    Return exactly one label:
    relevant
    not_relevant

    Return only the label."""

    response = llm.invoke(prompt)
    result = response.content.strip().lower()

    logger.info("Context evaluation result: %s", result)

    if result not in {"relevant", "not_relevant"}:
        logger.warning("Unexpected context evaluation result: %s", result)
        return "not_relevant"

    return result


def evaluate_answer(llm, query, context, answer):
    prompt = f"""You are evaluating an answer generated by a RAG system.

    Question:
    {query}

    Retrieved Context:
    {context}

    Generated Answer:
    {answer}

    Determine whether the generated answer is fully supported by the retrieved context.

    Return exactly one label:
    supported
    unsupported

    Return only the label."""

    response = llm.invoke(prompt)
    result = response.content.strip().lower()

    logger.info("Answer evaluation result: %s", result)

    if result not in {"supported", "unsupported"}:
        logger.warning("Unexpected answer evaluation result: %s", result)
        return "unsupported"

    return result